spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
      open-in-view : false
    defer-datasource-initialization: true

jwt:
  token:
    header: Authorization
    secret: ENC(J+nDUsXGhoG3RcAPZikqHFVJzZN8aDUAGJnUSPq2LtIE6eZKi0Rv9/+vDADvx8bsVAQZSiZ5d1V2jChOkLz+bf7FvDGt7cCEoHmt4oZjBwg/oA/TbDAn5DduMJ+6WPZ33Iwo0GE9uvU8+BofFo6UYw==)
    access-time: 3600000 # 60분
    refresh-time: 2628000000 # 한달
    issuer: F12
